package com.cantv.media.center.greendao;

import java.util.Map;

import android.database.sqlite.SQLiteDatabase;


import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig videoPlayerDaoConfig;

    private final VideoPlayerDao videoPlayerDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        videoPlayerDaoConfig = daoConfigMap.get(VideoPlayerDao.class).clone();
        videoPlayerDaoConfig.initIdentityScope(type);

        videoPlayerDao = new VideoPlayerDao(videoPlayerDaoConfig, this);

        registerDao(VideoPlayer.class, videoPlayerDao);
    }
    
    public void clear() {
        videoPlayerDaoConfig.getIdentityScope().clear();
    }

    public VideoPlayerDao getVideoPlayerDao() {
        return videoPlayerDao;
    }

}
