package com.cantv.media.center.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

/**
 * Entity mapped to table VIDEO_POSITION.
 */
public class VideoPlayer {

    private Long id;
    private String name;
    private Integer position;
    private String back1;
    private String back2;
    private String back3;

    public VideoPlayer() {
    }

    public VideoPlayer(Long id) {
        this.id = id;
    }

    public VideoPlayer(Long id, String name, Integer position, String back1, String back2, String back3) {
        this.id = id;
        this.name = name;
        this.position = position;
        this.back1 = back1;
        this.back2 = back2;
        this.back3 = back3;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getPosition() {
        return position;
    }

    public void setPosition(Integer position) {
        this.position = position;
    }

    public String getBack1() {
        return back1;
    }

    public void setBack1(String back1) {
        this.back1 = back1;
    }

    public String getBack2() {
        return back2;
    }

    public void setBack2(String back2) {
        this.back2 = back2;
    }

    public String getBack3() {
        return back3;
    }

    public void setBack3(String back3) {
        this.back3 = back3;
    }

}
